== Models Tool

=== Retinanet

==== Kurulum:
. https://github.com/tvsai/models_tool/tree/retinanetTool branch’ın
içeriği indirilir.

. Anaconda prompt terminatorü açılarak yeni bir environment oluşturulur
ve aktive edilir.
.. https://docs.conda.io/projects/conda/en/latest/userguide/tasks/manage-environments.html#creating-anenvironment-with-commands

NOTE: Environment'ı *python >= 3.6* bir sürüm ile oluşturmalısınız.

[start=3]
. Anaconda prompt terminatorü içerisinden içeriğin indirilen klasörün
içerisine gidilir. (*object_detection.py* ile aynı konumda olmalısınız). 

NOTE: Bu dökümanın kalanında bu klasörden *models_tool* olarak bahsedilecektir.

[start=4]

. https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5
adresine tıklayarak ilgili dosya indirilip. *models_tool/retinanet* klasörü içerisine konur.

. Gerekli kütüphaneler kurulur.
(retinanet/keras_retinanet/requirements.txt retinanet ile ilgili olanlar yer
almaktadır.) 

NOTE: tensorflow >= 2 sürümü sorunlar yaratabilir.

[start=6]
. *install_retinanet.sh* dosyası çalıştırılır. (komut satırından direkt çağırılarak çalıştırılabilir.) <<ref1,[1]>>

==== Veri Hazırlama:

. Veriler -öncelikle train ve test olmak üzere 2 gruba ayırılabilir.
. Her iki grup için de images, annotations klasörleri oluşturulmalıdır.(test
için ilk aşamada annotations klasörü boş kalabilir.)
.. *images:* Görüntülerin herhangi bir klasör içinde olmadan direkt yer aldığı klasördür. 
.. *annotation:* Pascal VOC formatında Annotation XML'lerinin,   herhangi bir klasör içinde olmadan direkt yer aldığı klasördür. 
. *models_tool/dataset* içerisindeki yapıya uygun olarak klasörler
yerleştirilir.
. *models_tool* klasörüne gidilirerek verilen komut çalıştırılır:
`python object_detection.py retinanet build_dataset`
. Açılan *debug* penceresinden image-annotation eşleşmeleri manuel olarak kontrol edilebilir(Çıkmak için *Esc* tuşunu kullanabilirsiniz).

==== Train:

. *models_tool* klasörüne gidilir. 

. Annotation ve image'lerin doğruluğunu kontrol etmek için komut:
`python object_detection.py retinanet debug`

. Eğitimi başlatmak için gerekli komut: 

----
python object_detection.py retinanet train --batch-size <1> 
--steps <2> 
--epochs <3>
----
<1> Sistem hafızası (RAM)'e bağlı bir parametredir verilerin kaçlı paketler halinde işleneceğini ifade eder. Sayı arttıkça RAM gereksinimi artar.

<2> Her bir epoch'da kaç adet batch alınacağını ifade eder.

<3> Veri üzerindeki toplam döngü sayısını ifade eder.

NOTE: Veri üzerinde epoch'lar ile tam tekrarlar yaratmak için *steps=Veri(imaj) Sayısı/batch size* olacak şekilde ayarlamayı unutmayın. 

Örneğin: 100 adet veriniz(imajınız) olsun. batch_size'ı 5 belirlediniz ve eğitim boyunca tüm veri üzerinde 30 tekrar yapmak istiyorsunuz: *steps = 20*, *epochs = 30*

[start=4]
. *Converting ve Evaluating:* Bu adımlar bu tool ile yapacağınız herhangi bir `python object_detection.py retinanet train` işlemi içerisinde otomatik yapılmaktadır. Ancak dilerseniz kendiniz daha sonra tekrar bunları çağırabilir ve kullanabilirsiniz:
.. Converting: `python object_detection.py retinanet convert`
.. Evaluating: `python object_detection.py retinanet evaluate`


==== Prediction:

. *models_tool* klasörüne gidilir.

. Prediction gerçekleştirmek için gerekli komut:
`python object_detection.py retinanet predict`

NOTE: Çıktılar varsayılan olarak *models_tool/retinanet/outputs* içerisinde yer alır.


==== References

[[ref1]]
[ 1 ] *install_retinanet.sh, build_dataset.py, predict.py* dosyaları verilen kaynaktan alınarak bu proje için düzenlemeler yapılarak kullanılmıştır. 
https://github.com/kapil-varshney/esri_retinanet[,role=external,window=_blank]
















